### ISSUE TITLE
Not skipping the bundle step on Debug configuration

### ISSUE THREAD

**Issue by ghost** [blargity/react-native-schemes-manager#21] opened 2017-08-01 15:57 UTC
### Steps to reproduce the behavior

We installed react-native-schemes-manager by following this [tutorial](https://medium.com/@ywongcode/building-multiple-versions-of-a-react-native-app-4361252ddde5) . When we build a Debug configuration, the react native packager is running steps that should be only for Release configuration like bundling the JS in one file, therefore making the build longer.

It seems like this [script](https://github.com/facebook/react-native/blob/master/scripts/react-native-xcode.sh) (`react-native-xcode.sh`) is not able to recognize whether it is Debug or Release configuration, and therefore not skipping the bundling part.

Info:
- React Native version: 0.44.3
- react-native-schemes-manager npm version: 1.0.0
- package.json
```
 "xcodeSchemes": {
    "Debug": [
      "App1.Debug",
      "App2.Debug"
    ],
    "Release": [
      "App1.Release",
      "App2.Release"
    ],
    "projectDirectory": "ios"
  }
```

- command:
```
react-native run-ios --scheme App1 --configuration App1.Debug
```

### Expected behavior
Should skip JavaScript bundling while in Debug configuration

### Actual behavior
JavaScript bundling:
```
(...)
bundle: start

bundle: finish
bundle: Writing bundle output to: /Users/me/Dev/mobile-apps-consumer/ios/build/Build/Products/App1.Debug-iphonesimulator/App1.app/main.jsbundle

bundle: Done writing bundle output

bundle: Copying 7 asset files

bundle: Done copying assets

+ [[ ! -n false ]]



PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks build/Build/Intermediates/mobileAppsConsumer.build/App1.Debug-iphonesimulator/mobileAppsConsumer.build/Script-364AF5F6FE9FE68F0A32E715A6885D4E.sh
    cd /Users/me/Dev/mobile-apps-consumer/ios
    /bin/sh -c /Users/me/Dev/mobile-apps-consumer/ios/build/Build/Intermediates/mobileAppsConsumer.build/App1.Debug-iphonesimulator/mobileAppsConsumer.build/Script-364AF5F6FE9FE68F0A32E715A6885D4E.sh

mkdir -p /Users/me/Dev/mobile-apps-consumer/ios/build/Build/Products/App1.Debug-iphonesimulator/App1.app/Frameworks

rsync -av --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/me/Dev/mobile-apps-consumer/ios/build/Build/Products/App1.Debug-iphonesimulator/GoogleToolboxForMac/GoogleToolboxForMac.framework" "/Users/me/Dev/mobile-apps-consumer/ios/build/Build/Products/App1.Debug-iphonesimulator/App1.app/Frameworks"

building file list ... done
(...)
```

PS: thanks for this awesome library, it really saved us a lot of time.

**Comment by blargity** [comment] 2017-08-10 07:57
Thanks for letting us know! Is there any chance you could have a look at what environment variables are getting passed into the script?

In particular, the values of `$CONFIGURATION` and `$DEVELOPMENT_BUILD_CONFIGURATIONS` would help.

That script is a direct copy of the Facebook version with a tiny change to expand on how it figures out that you're running in Debug or not, which it sounds like isn't working for you. It'd be useful to be able to try to reproduce the problem with closer environment to yours.

**Comment by sneerin** [comment] 2017-09-08 18:41
For me, debug is also not working

**Comment by sneerin** [comment] 2017-09-08 21:09
how does xcode pass the DEV arg to react?

**Comment by sneerin** [comment] 2017-09-09 19:12
I checked the schemas in react project, in the node modules, they are correct https://www.dropbox.com/s/yall3mq7o0luty9/Screenshot%202017-09-09%2022.11.50.png?dl=0

**Comment by D1no** [comment] 2017-09-22 11:56
Also would like to check in. Dynamic links are one of the large building blocks missing. Especially since Dynamic Links got recently quite a lot more integration for attribution measurements. http://firebase.googleblog.com/2017/09/whats-new-with-firebase-dynamic-links.html

**Comment by blargity** [comment] 2017-10-05 23:14
I'll see if I can reproduce this the next time I've got a chance to dig into this project. We've changed the if statement for the command a few times now and I'm not 100% convinced that it's correct in all cases yet, so a reproduction case would probably help.

XCode passes some environment variables to this script: https://github.com/Thinkmill/react-native-schemes-manager/blob/master/lib/react-native-xcode.sh

That script is a copy of the one Facebook distributes with React native except for the changes to determine if we're running a debug scheme. The original Facebook script just checks if the scheme name is `Debug`.

**Comment by fryossi** [comment] 2018-02-14 09:17
I'm facing the same error.
In my case the scheme name and the configuration name are not identical.
`$DEVELOPMENT_BUILD_CONFIGURATIONS` contains a list of scheme names and `$CONFIGURATION` is the actual configuration name.
switching the scheme name with the configuration name in `$DEVELOPMENT_BUILD_CONFIGURATIONS` fix this.

react-native: 0.52.0
react: 16.2.0
react-native-schemes-manager: 1.0.1

**Comment by blargity** [comment] 2018-04-09 12:01
@fryossi has this been fixed in the latest versions?

**Comment by fryossi** [comment] 2018-04-09 12:25
@blargity I didn't try the new version. I've changed the scheme name to be as same as the configuration name so everything works fine.

**Comment by akriger** [comment] 2018-04-20 19:00
@blargity I am running into this issue with my build as well. I have one scheme with a debug, beta, and release configuration. When running the debug configuration via command line(react-native run-ios --configuration Debug) I get the following error when the app launches:

error: bundling failed: NotFoundError: Cannot find entry file index.js in any of the roots: ["/Users/akriger/Repos/WESConnect"]

I also tried running directly from xCode and have the same issue. 

Any help would be appreciated

react-native: 0.55.2
react: 16.3.1
react-native-schemes-manager: 1.0.4

**Comment by blargity** [comment] 2018-08-06 03:31
In that case I'll go ahead and close this issue. If anyone's still experiencing this, a reproduction case would help heaps!

**Closed by blargity** 2018-08-06 03:31 UTC
